apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-deflector
  namespace: traffic-deflector
spec:
  selector:
    matchLabels:
      app: traffic-deflector
  replicas: 3
  template:
    metadata:
      labels:
        app: traffic-deflector
    spec:
      serviceAccountName: traffic-deflector
      containers:
      - image: ghcr.io/jille/k8s-traffic-deflector:v1.0.0
        name: traffic-deflector
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: traffic-deflector
  namespace: traffic-deflector
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: traffic-deflector
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traffic-deflector
  namespace: traffic-deflector
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: healthcheck.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traffic-deflector
            port:
              number: 80
  tls:
  - hosts:
    - healthcheck.example.com
    secretName: traffic-deflector-https
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: traffic-deflector
  namespace: traffic-deflector
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: traffic-deflector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffic-deflector
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-deflector
  namespace: traffic-deflector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traffic-deflector
roleRef:
  kind: ClusterRole
  name: traffic-deflector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: traffic-deflector
  namespace: traffic-deflector
